<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\{
    PropertiesController,
    PropertyImagesController
};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
| Changes made by Qusai 1/7/23
| 1. Added routes that requires a user to be signed in to auth middleware
| 2. Replaced properties CRUD routes with resource method
| 3. Named routes to better refrence them in code
| 4. Added routes for property images - still not done yet
*/

/*
| routes generated by resource method:
|    GET /posts - posts.index
|    GET /posts/create - posts.create
|    POST /posts - posts.store
|    GET /posts/{post} - posts.show
|    GET /posts/{post}/edit - posts.edit
|    PUT/PATCH /posts/{post} - posts.update
|    DELETE /posts/{post} - posts.destroy
*/


Route::middleware(['auth:sanctum'])->group(function () {
    Route::resource('posts', PropertiesController::class);
    Route::resource('properties/{property}/images', PropertyImagesController::class);
    Route::get('myproperties', [PropertiesController::class, 'my_properties_index'])->name('my_properties');
    Route::get('favorites', [PropertiesController::class, 'favorites'])->name('properties.favorites');
    Route::post('properties/{post}/favorite', [PropertiesController::class, 'change_favorite_state'])->where('post', '[0-9]+')->name('properties.favorite');
    Route::post('/logout', [AuthController::class, 'logout']);
});

Route::post('/register', [AuthController::class, 'register'])->name('register');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::post('verification', [AuthController::class, 'verification'])->name('verification');


// Route::get('sendSMS', [AuthController::class , 'sendSMS']);
// Route::get('generateOtp', [AuthController::class , 'generateOtp']);
// Route::get('test', [PropertiesController::class , 'test']);
// Route::get('test2', [PropertiesController::class , 'test2']);

/* TODO:
add images table to user
add balance attribute to user
*/
